export const PATH: { [key: string]: string } = {
    forms: "/home/main/forms",
    userManagement: "/home/admin/users",
    influencers: "/home/main/influencers",
    newInfluencer: "/home/talent/new/influencer",
    celebrities: "/home/talent/head/celebrities",
    newCelebrity: "/home/talent/new/celebrity",
    rateLogs: "/home/talent/logs",
    newRateLog: "/home/talent/new/rateLog",
    newTimeForm: "/home/talent/new/timeForm",
    newSalesBrief: "/home/sales/newBrief",
    readyBriefs: "/home/sales/readyBriefs/",
    sentBriefs: "/home/sales/sentBriefs/",
    allBriefs: "/home/main/allBriefs",
    talentTasks: "/home/talent/head/execTasks",
    personTasks: "/home/talent/tasks/",
    registerUser: "/home/admin/register",
    editProfile: "/home/main/editProfile",
    salesGuide: "/home/main/salesGuide",
    adminGuide: "/home/main/adminGuide",
    talentGuide: "/home/main/talentGuide",
    influencerRating: "/home/talent/influencerRating/",
    viewBrief: "/home/talent/viewBrief/",
    editUser: "/home/admin/edit/",
    viewCampaigns: "/home/campaign/viewCampaigns",
};
